window.KA_DARSLAR = [
  { id: 1, bob: 1, paragraf: "1-§", nom: "Kvadrat funksiyaning ta'rifi", qisqa: "Nima uchun y = ax² + bx + c kvadrat funksiya deyiladi.", vizual: "Formula qismlari a, b, c ga ajraladi. a = 0 bo'lsa chiziqli chiziq qoladi." },
  { id: 2, bob: 1, paragraf: "2-§", nom: "y = x² funksiya", qisqa: "Eng sodda parabola, uchi va simmetriya o'qi.", vizual: "Nuqtalar jadvalidan parabola chiziladi. Simmetriya jonlanadi." },
  { id: 3, bob: 1, paragraf: "3-§", nom: "y = ax² funksiya", qisqa: "a tarmoqlarni ochadi, yopadi yoki ag'daradi.", vizual: "a slayderi: ingichka-keng, tepaga-pastga." },
  { id: 4, bob: 1, paragraf: "4-§", nom: "y = ax² + bx + c funksiya", qisqa: "Uchi siljiydi. To'la kvadrat va parallel ko'chirish.", vizual: "a, b, c slayderlari. Uchi va o'q harakatda." },
  { id: 5, bob: 1, paragraf: "5-§", nom: "Kvadrat funksiyaning grafigini yasash", qisqa: "Besh qadam: uchi, o'q, nollar, juft nuqtalar, chiziq.", vizual: "Har qadam alohida yonadi. Doskada ketma-ket yasash." },
  { id: 6, bob: 1, paragraf: "6-§", nom: "Kvadrat tengsizlik va uning yechimi", qisqa: "ax² + bx + c > 0 nima degani.", vizual: "Ko'paytuvchilar ishorasi son o'qida." },
  { id: 7, bob: 1, paragraf: "7-§", nom: "Tengsizlikni grafik bilan yechish", qisqa: "Parabola Ox dan yuqoridami, pastdami?", vizual: "Parabola bo'yaladi. Yechim oralig'i yonadi." },
  { id: 8, bob: 1, paragraf: "8-§", nom: "Intervallar usuli", qisqa: "Nollar o'qni bo'laklarga ajratadi.", vizual: "Ishora zanjiri. Plus-minus almasinadi." },
  { id: 9, bob: 1, paragraf: "9-§", nom: "Funksiyaning aniqlanish sohasi", qisqa: "Qayerda ifoda umuman mavjud.", vizual: "Taqiqlangan nuqtalar o'qda teshiladi." },
  { id: 10, bob: 1, paragraf: "10-§", nom: "Funksiyaning o'sishi va kamayishi", qisqa: "Qaysi oraliqda grafik ko'tariladi yoki tushadi.", vizual: "Uchdan chap va o'ng rang bilan ajraladi." },
  { id: 11, bob: 1, paragraf: "11-§", nom: "Funksiyaning juftligi va toqligi", qisqa: "Oy ga yoki origoga nisbatan simmetriya.", vizual: "Chap tomon o'ngga bukiladi." },
  { id: 12, bob: 1, paragraf: "12-§", nom: "Daraja qatnashgan tenglama va tengsizlik", qisqa: "Ildiz va daraja qachon ishlaydi.", vizual: "Ruxsat etilgan soha avval chiziladi." },
  { id: 13, bob: 2, paragraf: "13-§", nom: "Kvadrat qatnashgan sodda sistemalar", qisqa: "Parabola va to'g'ri chiziq kesishishi.", vizual: "Ikki grafik, kesishish nuqtalari yonadi." },
  { id: 14, bob: 2, paragraf: "14-§", nom: "Sistemani yechishning turli usullari", qisqa: "Qo'yish, qo'shish — bir xil nuqta, boshqa yo'l.", vizual: "Usul almashsa ham nuqta joyida qoladi." },
  { id: 15, bob: 2, paragraf: "15-§", nom: "Kvadrat tengsizliklar sistemasi", qisqa: "Ikki shartning umumiy qismi.", vizual: "Ikki oraliq ustma-ust. Kesishma qoladi." },
  { id: 16, bob: 2, paragraf: "16-§", nom: "Sodda tengsizliklarni isbotlash", qisqa: "Nima uchun doim rost yoki yolg'on.", vizual: "Ayirma grafigi noldan yuqorida turadi." },
  { id: 17, bob: 3, paragraf: "17-§", nom: "Burchakning radian o'lchovi", qisqa: "Daraja o'rniga yoy uzunligi.", vizual: "Yoy va radius taqqoslanadi. π jonlanadi." },
  { id: 18, bob: 3, paragraf: "18-§", nom: "Nuqtani koordinatalar boshi atrofida burish", qisqa: "Nuqta aylanada yuradi.", vizual: "Nuqtani sichqoncha bilan burish." },
  { id: 19, bob: 3, paragraf: "19-§", nom: "sin, cos, tg, ctg ta'riflari", qisqa: "Birlik aylananing to'rt soni.", vizual: "Uchburchak aylanada. Uzunliklar o'qqa tushadi." },
  { id: 20, bob: 3, paragraf: "20-§", nom: "Sinus, kosinus va tangens ishoralari", qisqa: "Qaysi chorakda plus, qaysida minus.", vizual: "Choraklar ranglanadi." },
  { id: 21, bob: 3, paragraf: "21-§", nom: "sin, cos, tg orasidagi munosabatlar", qisqa: "Asosiy ayniyatlar qayerdan chiqadi.", vizual: "Pifagor aylanada: x² + y² = 1." },
  { id: 22, bob: 3, paragraf: "22-§", nom: "Trigonometrik ayniyatlar", qisqa: "Bir ifoda boshqasiga teng.", vizual: "Chap va o'ng tomon bir xil songa tushadi." },
  { id: 23, bob: 3, paragraf: "23-§", nom: "α va −α burchaklar", qisqa: "Qarama-qarshi burchakning simmetriyasi.", vizual: "Nuqta Ox ga nazar tashlanadi." },
  { id: 24, bob: 3, paragraf: "24-§", nom: "Qo'shish formulalari", qisqa: "Ikki burchak yig'indisining sin va cos i.", vizual: "Ikki burilish ketma-ket qo'shiladi." },
  { id: 25, bob: 3, paragraf: "25-§", nom: "Ikkilangan burchak", qisqa: "2α qanday yoziladi.", vizual: "Burchak ikki barobar ochiladi." },
  { id: 26, bob: 3, paragraf: "26-§", nom: "Keltirish formulalari", qisqa: "90° va 180° ga siljish.", vizual: "Aylana chorakma-chorak aylanadi." },
  { id: 27, bob: 3, paragraf: "27-§", nom: "Sinus va kosinus yig'indisi, ayirmasi", qisqa: "Yig'indi ko'paytmaga aylanadi.", vizual: "Ikki to'lqin qo'shilib yangi to'lqinga o'tadi." },
  { id: 28, bob: 4, paragraf: "28-§", nom: "Sonli ketma-ketliklar", qisqa: "Hadlar qator bo'lib yuradi.", vizual: "Nuqtalar o'qda paydo bo'ladi." },
  { id: 29, bob: 4, paragraf: "29-§", nom: "Arifmetik progressiya", qisqa: "Har safar bir xil qo'shiladi.", vizual: "Teng qadamlar. d slayderi." },
  { id: 30, bob: 4, paragraf: "30-§", nom: "Arifmetik progressiya yig'indisi", qisqa: "Birinchi n ta had qanday yig'iladi.", vizual: "Ustunlar to'planadi. Formula jonlanadi." },
  { id: 31, bob: 4, paragraf: "31-§", nom: "Geometrik progressiya", qisqa: "Har safar bir xil songa ko'paytiriladi.", vizual: "q slayderi. Qadamlar kengayadi yoki siqiladi." },
  { id: 32, bob: 4, paragraf: "32-§", nom: "Geometrik progressiya yig'indisi", qisqa: "n ta hadning yig'indisi.", vizual: "Maydoncha qo'shiladi." },
  { id: 33, bob: 4, paragraf: "33-§", nom: "Cheksiz kamayuvchi geometrik progressiya", qisqa: "Cheksiz qo'shsa ham son chegaraga intiladi.", vizual: "Kvadratning ichida kvadrat. Yig'indi to'xtaydi." },
  { id: 34, bob: 5, paragraf: "34-§", nom: "Hodisalar", qisqa: "Muqarrar, imkonsiz, tasodifiy.", vizual: "Quti ichidan chiqadigan natijalar." },
  { id: 35, bob: 5, paragraf: "35-§", nom: "Hodisaning ehtimolligi", qisqa: "Qulay holatlar / barcha holatlar.", vizual: "Bo'laklar bo'yaladi. Kasr jonlanadi." },
  { id: 36, bob: 5, paragraf: "36-§", nom: "Nisbiy chastota", qisqa: "Ko'p urinishdan keyin ulush barqarorlashadi.", vizual: "Urinishlar sanagichi va ustunlar." },
  { id: 37, bob: 5, paragraf: "37-§", nom: "Tasodifiy miqdorlar", qisqa: "Natija son bilan o'lchanadi.", vizual: "Jadval va nuqtalar." },
  { id: 38, bob: 5, paragraf: "38-§", nom: "Sonli xarakteristikalar", qisqa: "O'rtacha, moda, mediana.", vizual: "Nuqtalar og'irlik markaziga tortiladi." }
];

window.KA_BOBLAR = [
  { id: 1, roman: "I", nom: "Kvadrat funksiya. Kvadrat tengsizliklar", izoh: "Parabola va uning og'zaki tili." },
  { id: 2, roman: "II", nom: "Tenglamalar va tengsizliklar sistemalari", izoh: "Ikki shart — bitta javob." },
  { id: 3, roman: "III", nom: "Trigonometriya elementlari", izoh: "Burchak aylanada yashaydi." },
  { id: 4, roman: "IV", nom: "Sonli ketma-ketliklar. Progressiyalar", izoh: "Qator qanday o'sadi." },
  { id: 5, roman: "V", nom: "Ehtimollik va statistika elementlari", izoh: "Tasodif ham hisoblanadi." }
];
